### ISSUE TITLE
Layout Error

### ISSUE THREAD

**Issue by JmanNZ** [PricelessToolkit/ESPClicker#8]
Hi
The render in the readme has the ULN2003 pin 1 in the wrong place. Should be the other way round.
Clicker is built and works perfectly thank you.

**Comment by PricelessToolkit** [comment]
Hi, Thank you! for supporting my work, can you explain in more detail? It's an error in the "Schematic render"?

**Comment by JmanNZ** [comment]
Hi 
The dot showing pin 1 of the ULN2003 is incorrect. Should be on the other side.
The green dot is correct in the Pic
 
![image](https://github.com/PricelessToolkit/ESPClicker/assets/27104214/e5267e23-4552-435b-a7e1-62a731679300)

Regards

**Comment by PricelessToolkit** [comment]
> Hi The dot showing pin 1 of the ULN2003 is incorrect. Should be on the other side. The green dot is correct in the Pic
> 
> ![image](https://user-images.githubusercontent.com/27104214/256934992-e5267e23-4552-435b-a7e1-62a731679300.png)
> 
> Regards

Thanks, I changed the picture Thanks.
